### PR TITLE
Moved icons into icon folder

### PR DESCRIPTION
**Pull request by woshibiantai**

### CODE REVIEW

**Comment by emileber** [comment]
This is related to #16 

@woshibiantai It's best if you ask in the issue for details and if it's still up for grab.

**Comment by GabLeRoux** [comment]
Ah after taking a look, just let me handle this, I’ll move everything asset related in an `assets` folder and will have to update html files and also grunt script to point to right location, and I’ll have to verify that generated site has all of the assets ok.

If I change the images folder, I’ll have to add a task so it gets moved to root on the deployed site as I don’t want the picture urls to change (google image results, etc).

**Comment by emileber** [comment]
@GabLeRoux You should retag the issue because you've already received another PR #19

**Comment by GabLeRoux** [comment]
Ahah I didn’t expect that, will open my laptop in less than an hour and I’ll sort this out. Thanks! :D

**Comment by GabLeRoux** [comment]
Closing as current pr moves icons to a folder, but doesn't update urls in html files. My bad as the requirements were not clear enough.

**Pull request closed without merging**
